spring:
  application:
    name: distribution-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
  # 表示是否从eureka server 获取注册信息, 默认是true, 如果这是一个单节点的 eureka server
  # 不需要同步其他节点的数据, 设置为 false
    fetch-registry: false
  # 是否将自己注册到 eureka server ,默认是true, 由于目前是单节点的 eureka server
  # 需要设置为 false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
  #  renewal-percent-threshold: 0.45